configoptions="
--disable-short-tags \
--enable-bcmath \
--enable-calendar \
--enable-cgi \
--enable-cli \
--enable-exif \
--enable-fpm \
--enable-ftp \
--enable-gd \
--enable-intl \
--enable-mbstring \
--enable-opcache \
--enable-pcntl \
--enable-soap \
--enable-sockets \
--enable-wddx \
--with-curl \
--with-freetype \
--with-gettext \
--with-gmp \
--with-jpeg \
--with-layout=GNU \
--with-ldap \
--with-libzip \
--with-mysqli \
--with-openssl \
--with-pdo-mysql \
--with-pear \
--with-png-dir \
--with-readline \
--with-sodium \
--with-xsl \
--with-zip \
--with-zlib
"
